// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdfqlbslaoogzfkczosi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZnFsYnNsYW9vZ3pma2N6b3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MjU2NTksImV4cCI6MjA2NzQwMTY1OX0.PIAfber5EpdzCAZHyKUAZE4SRxzds_OClEfKtc36UG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});